name: kenali_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.7.0

  # Jika kamu butuh, tambahkan package lain disini
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2

flutter:
  assets:
    - assets/images/logo_kenali.png
    # - assets/fonts/

  fonts:
    - family: Poppins
      # - family: MyIcons
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        # - asset: assets/fonts/MyIcons.ttf
