import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          MenuBeranda(),
        ]),
      ),
    );
  }
}

class MenuBeranda extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFF67DCA8)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 93,
                child: Container(
                  width: 360,
                  height: 707,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFB1F2BC),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(47),
                        topRight: Radius.circular(47),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 720,
                child: Container(
                  width: 360,
                  height: 80,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF67DCA8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(21),
                        topRight: Radius.circular(21),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 147,
                top: 735,
                child: Container(
                  width: 65,
                  height: 56,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF88EAAD),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                  ),
                ),
              ),
              Positioned(
                left: 158,
                top: 738,
                child: Container(width: 50, height: 50, child: Stack()),
              ),
              Positioned(
                left: 58,
                top: 738,
                child: Container(width: 50, height: 50, child: Stack()),
              ),
              Positioned(
                left: 258,
                top: 735,
                child: Container(width: 50, height: 50, child: Stack()),
              ),
              Positioned(
                left: 7,
                top: 21,
                child: Container(
                  padding: const EdgeInsets.all(10),
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x0726334D),
                        blurRadius: 5,
                        offset: Offset(0, 2),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    spacing: 10,
                    children: [
                      Container(width: 30, height: 30, child: Stack()),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 113,
                child: Container(
                  width: 325,
                  height: 524,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF9F7F8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 66,
                top: 30,
                child: SizedBox(
                  width: 161,
                  height: 31,
                  child: Text(
                    'Selamat Datang,\nMoch. Rizki Romadhoni',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Montserrat',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 188,
                child: Container(
                  width: 266,
                  height: 60,
                  decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 50,
                top: 218,
                child: SizedBox(
                  width: 61,
                  height: 12,
                  child: Text(
                    'Tanggal',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 50,
                child: Text(
                  'Senin, 10-April-2025',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 257,
                top: 28,
                child: SizedBox(
                  width: 84,
                  height: 28,
                  child: Text(
                    '10.00',
                    textAlign: TextAlign.right,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 131,
                child: Text(
                  'Hasil Prediksi Tersimpan',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 245,
                top: 210,
                
                child: GestureDetector(
                  onTap: () {
  Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => detail_prediksi()),
  );
      print('Detail ditekan');
                  }
      
                  child: Container(
                    width: 47,
                    height: 21,
                    decoration: BoxDecoration(color: const Color(0xFF0400FF)),
                  ),
                ),
              ),
              Positioned(
                left: 249,
                top: 212,
                child: SizedBox(
                  width: 34,
                  height: 13,
                  child: Text(
                    'Detail',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 50,
                top: 198,
                child: SizedBox(
                  width: 61,
                  height: 12,
                  child: Text(
                    'Prediksi 1',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 278,
                child: Container(
                  width: 266,
                  height: 60,
                  decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 50,
                top: 308,
                child: SizedBox(
                  width: 61,
                  height: 12,
                  child: Text(
                    'Tanggal',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 245,
                top: 300,
                child: Container(
                  width: 47,
                  height: 21,
                  decoration: BoxDecoration(color: const Color(0xFF0400FF)),
                ),
              ),
              Positioned(
                left: 249,
                top: 302,
                child: SizedBox(
                  width: 34,
                  height: 13,
                  child: Text(
                    'Detail',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 50,
                top: 288,
                child: SizedBox(
                  width: 61,
                  height: 12,
                  child: Text(
                    'Prediksi 2',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 370,
                child: Container(
                  width: 266,
                  height: 60,
                  decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 50,
                top: 400,
                child: SizedBox(
                  width: 61,
                  height: 12,
                  child: Text(
                    'Tanggal',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 245,
                top: 392,
                child: Container(
                  width: 47,
                  height: 21,
                  decoration: BoxDecoration(color: const Color(0xFF0400FF)),
                ),
              ),
              Positioned(
                left: 249,
                top: 394,
                child: SizedBox(
                  width: 34,
                  height: 13,
                  child: Text(
                    'Detail',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 50,
                top: 380,
                child: SizedBox(
                  width: 61,
                  height: 12,
                  child: Text(
                    'Prediksi 3',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}